exclude-labels:
  - 'Ignore for release'
categories:
  - title: '📌 Major improvements'
    labels:
      - 'Major'
  - title: '⚛ Core improvements'
    labels:
      - 'Core'
  - title: '🔗 Connectors improvements'
    labels:
      - 'Connectors'
      - 'Connector'
      - 'Modbus'
      - 'MQTT'
      - 'BACnet'
      - 'BLE'
      - 'CAN'
      - 'FTP'
      - 'KNX'
      - 'OCPP'
      - 'ODBC'
      - 'OPC-UA'
      - 'Request'
      - 'REST'
      - 'SNMP'
      - 'Socket'
      - 'XMPP'
  - title: '🗄 Storages improvements'
    labels:
      - 'Storages'
      - 'Storage'
      - 'Memory'
      - 'File'
      - 'SQLite'
  - title: '🐛 Bug fixes'
    labels:
      - 'Bug'
  - title: 'Other'
    labels:
      - 'Other'
      - 'Tests'
template: |
  ## What's Changed
  $CHANGES
